#!/bin/bash -e

OPENSSL_FILE="./openssl.cnf"

write_openssl() {
	cat > "$OPENSSL_FILE" <<-OPENSSL
	# OpenSSL configuration file.
	
	# Establish working directory.
	
	dir                                     = .
	
	[ ca ]
	default_ca                              = CA_default
	
	[ CA_default ]
	default_bits                            = 2048
	default_md                              = sha256
	serial                                  = \$dir/serial
	database                                = \$dir/certindex.txt
	new_certs_dir                           = \$dir/certs
	certificate                             = \$dir/cacert.crt
	private_key                             = \$dir/private/cakey.crt
	default_days                            = 365
	preserve                                = no
	email_in_dn                             = no
	nameopt                                 = default_ca
	certopt                                 = default_ca
	policy                                  = policy_match
	copy_extensions                         = copy
	
	[ policy_match ]
	countryName                             = optional
	stateOrProvinceName                     = optional
	organizationName                        = optional
	organizationalUnitName                  = optional
	commonName                              = supplied
	emailAddress                            = optional
	
	[ req ]
	default_bits                            = 2048                  # Size of keys
	default_md                              = sha256
	default_keyfile                         = key.crt               # name of generated keys
	string_mask                             = nombstr               # permitted characters
	distinguished_name                      = req_distinguished_name
	req_extensions                          = v3_req
	
	[ req_distinguished_name ]
	# Variable name                         Prompt string
	#-------------------------        ----------------------------------
	0.organizationName                      = Organization Name (company)
	organizationalUnitName                  = Organizational Unit Name (department, division)
	emailAddress                            = Email Address
	emailAddress_max                        = 40
	localityName                            = Locality Name (city, district)
	stateOrProvinceName                     = State or Province Name (full name)
	countryName                             = Country Name (2 letter code)
	countryName_min                         = 2
	countryName_max                         = 2
	commonName                              = Common Name (hostname, IP, or your name)
	commonName_max                          = 64
	
	[ v3_ca ]
	basicConstraints                        = CA:TRUE
	subjectKeyIdentifier                    = hash
	authorityKeyIdentifier                  = keyid:always,issuer:always
	
	[ v3_req ]
	basicConstraints                        = CA:FALSE
	subjectKeyIdentifier                    = hash
	keyUsage                                = nonRepudiation, digitalSignature, keyEncipherment
	extendedKeyUsage                        = serverAuth, clientAuth, codeSigning, emailProtection
	OPENSSL
}

ACTION="$1"
if [[ $ACTION == "ca" ]] ; then
	SUBJECT="${2:-/CN=OwnCA}"

	touch certindex.txt
	mkdir -p certs/
	mkdir -p private/

	if [[ ! -f "$OPENSSL_FILE" ]] ; then
		write_openssl
	fi

	openssl req -batch -new -x509 \
		-config "$OPENSSL_FILE" \
		-subj "$SUBJECT" -extensions v3_ca -nodes \
		-keyout private/cakey.crt \
		-out cacert.crt -days 3650
elif [[ $ACTION == "cert" ]] ; then
	CERT_HOST="$2"
	if [[ -z $CERT_HOST ]] ; then
		echo "Usage: $0 cert HOSTNAME"
		exit 1
	fi

	if [[ ! -e private/cakey.crt ]] ; then
		echo "First generate a CA using $0 ca"
		exit 2
	fi

	mkdir "$CERT_HOST"
	openssl req -new -nodes \
		-subj "/CN=$CERT_HOST" \
		-addext "subjectAltName = DNS:$CERT_HOST" \
		-out "./$CERT_HOST/$CERT_HOST.req" \
		-keyout "./$CERT_HOST/$CERT_HOST.key"

	openssl ca -batch -create_serial \
		-config "$OPENSSL_FILE" \
		-in "./$CERT_HOST/$CERT_HOST.req" \
		-out "./$CERT_HOST/$CERT_HOST.crt"
else
	echo "Usage: $0 ca [SUBJECT]"
	echo "Usage: $0 cert HOSTNAME"
	exit 1
fi
